version: "2"

services:
  redis:
    image: redis
    restart: always
  mongo:
    image: mongo
    restart: always
  web:
    build: .
    command: yarn start
    ports:
      - "8124:8124"
    volumes:
      - .:/app
    depends_on:
      - redis
      - mongo
    env_file: .env
